### ISSUE TITLE
Has version 4.3.5 been released?

### ISSUE THREAD

**Issue by ryandesign** [vlabella/GLE#37]
The ChangeLog suggests that version 4.3.5 was released in March 2024:

https://github.com/vlabella/GLE/blob/9319f6c2a3a71b19364b427817143441fb35a38e/doc/ChangeLog.txt#L1-L2

but the latest tag in this repository is 4.3.4. If 4.3.5 was released, please create the tag and the GitHub release. If 4.3.5 has not been released, there shouldn't be a release date for that version in the ChangeLog; it should say something like "unreleased".

**Comment by vlabella** [comment]
No it has not been released yet.  Features added since last release that are available are added to the change log to keep track of them.  Users can get those if they build from source.  Maybe adding the word "unreleased" would be good, or some other way of identifying the features that get added during development that are now available in the current source
